-- Seed legado descontinuado.
--
-- Use seeds versionados em backend/database/seeds + script de seed:
--   npm run seed
--   npm run seed:status
--
-- Para novos dados de populacao, crie um novo arquivo numerado em:
--   backend/database/seeds/0002_nome_do_seed.sql
--
-- Este arquivo permanece intencionalmente sem inserts para evitar duplicacoes acidentais.
